// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TallerHernandez.Data;

namespace TallerHernandez.Migrations
{
    [DbContext(typeof(TallerHernandezContext))]
    [Migration("20200925194256_nombre")]
    partial class nombre
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TallerHernandez.Models.Repuesto", b =>
            {
                b.Property<int>("repuestoID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("estadorespuesto")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("anio")
                    .HasColumnType("int");

                b.Property<int>("cantidad")
                    .HasColumnType("int");

                b.Property<string>("categoria")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("tipo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("repuestoID");

                b.ToTable("Repuesto");
            });


#pragma warning restore 612, 618
        }
    }
}
